name: Build Listener Clients

on:
  push:
    paths:
      - 'listener_clients/**'
      - '.github/workflows/build-listener-clients.yaml'
  pull_request:
    paths:
      - 'listener_clients/**'
      - '.github/workflows/build-listener-clients.yaml'
  workflow_dispatch:

jobs:
  build_m5stickc-listener:
    name: Build M5StickC Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json
          fqbn: 'esp32:esp32:m5stack_stickc'
          libraries: |
            - source-url: https://github.com/m5stack/M5StickC/archive/refs/tags/0.3.0.zip
            - source-url: https://github.com/m5stack/M5StickC-Plus/archive/refs/tags/0.1.0.zip
            - name: WebSockets
            - name: WiFiManager
            - name: MultiButton
            - name: Arduino_JSON
          cli-compile-flags: |
            - --export-binaries
          sketch-paths: |
            - listener_clients/m5stickc-listener
          enable-deltas-report: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'TallyArbiter-Listener-M5StickC'
          path: 'listener_clients/m5stickc-listener/build/esp32.esp32.m5stack_stickc'

  build_m5atom-listener:
    name: Build M5Atom Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json
          fqbn: 'esp32:esp32:m5stack_atom'
          libraries: |
            - source-url: https://github.com/m5stack/M5Atom/archive/refs/tags/0.1.3.zip
            - name: WebSockets
            - name: WiFiManager
            - name: MultiButton
            - name: Arduino_JSON
            - name: FastLED
          cli-compile-flags: |
            - --export-binaries
          sketch-paths: |
            - listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom
          enable-deltas-report: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'TallyArbiter-Listener-M5Atom'
          path: 'listener_clients/M5AtomMatrix-listener/tallyarbiter-m5atom/build/esp32.esp32.m5stack_atom'

  build_esp32-neopixel-listener:
    name: Build ESP32 NeoPixel Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json
          fqbn: 'esp32:esp32:esp32'
          libraries: |
            - name: WebSockets
            - name: WiFiManager
            - name: MultiButton
            - name: Arduino_JSON
            - name: Adafruit NeoPixel
          cli-compile-flags: |
            - --export-binaries
          sketch-paths: |
            - listener_clients/esp32-neopixel-listener
          enable-deltas-report: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'TallyArbiter-Listener-ESP32-NeoPixel'
          path: 'listener_clients/esp32-neopixel-listener/build/esp32.esp32.esp32'

  build_TTGO-listener:
    strategy:
      fail-fast: false
      matrix:
        board:
          - fqbn: esp32:esp32:ttgo-t1
            name: TTGO T1
          - fqbn: esp32:esp32:ttgo-t7-v13-mini32
            name: TTGO T7 v13 Mini32
          - fqbn: esp32:esp32:ttgo-t7-v14-mini32
            name: TTGO T7 v14 Mini32
          - fqbn: esp32:esp32:twatch
            name: TTGO T-Watch
    name: Build ${{ matrix.board.name }} Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup TFT_eSPI and select User Setup
        run: |
          git clone https://github.com/Bodmer/TFT_eSPI/
          cd TFT_eSPI
          sed -i 's/#include <User_Setup.h>/\/\/#include <User_Setup.h>/g' User_Setup_Select.h
          sed -i 's/\/\/#include <User_Setups\/Setup22_TTGO_T4.h>/#include <User_Setups\/Setup22_TTGO_T4.h>/g' User_Setup_Select.h
      - uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: esp32:esp32
              source-url: https://dl.espressif.com/dl/package_esp32_index.json
          fqbn: ${{ matrix.board.fqbn }}
          libraries: |
            - name: WebSockets
            - name: WiFiManager
            - name: MultiButton
            - name: Arduino_JSON
            - source-path: TFT_eSPI
          cli-compile-flags: |
            - --export-binaries
          sketch-paths: |
            - listener_clients/TTGO_T-listener
          enable-deltas-report: true
      - name: Get FQBN build dir for ${{ matrix.board.name }}
        run: |
          RAW_FQBN="${{ matrix.board.fqbn }}"
          FQBN_REPLACED=$(echo $RAW_FQBN | sed 's/:/./g')
          echo "FQBN_REPLACED=$FQBN_REPLACED" >> $GITHUB_ENV
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'TallyArbiter-Listener-${{ matrix.board.name }}'
          path: 'listener_clients/TTGO_T-listener/build/${{ env.FQBN_REPLACED }}'

  analyse_blink1-listener:
    name: Analyse Blink1 Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prosepector
        run: pip install prospector[with_everything]
      - name: Analyse
        working-directory: listener_clients/blink1-listener
        run: prospector -W pyroma -0

  analyse_blinkt-listener:
    name: Analyse Pimoroni Blinkt Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prosepector
        run: pip install prospector[with_everything]
      - name: Analyse
        working-directory: listener_clients/pimoroni-blinkt-listener
        run: prospector -W pyroma -0

  analyse_gpo-listener:
    name: Analyse GPO Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install prosepector
        run: pip install prospector[with_everything]
      - name: Analyse
        working-directory: listener_clients/gpo-listener
        run: prospector -W pyroma -0

  analyse_relay-listener:
    name: Analyse Relay Listener
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
    #- name: Install dependencies
    #  working-directory: listener_clients/relay-listener
    #  run: |
    #    sudo apt install libudev-dev libusb-1.0-0 libusb-1.0-0-dev
    #    npm install
    #    npm install --global eslint
    #- name: Run eslint
    #  working-directory: listener_clients/relay-listener
    #  run: eslint index.js || exit 0
