name: Close Stale Issues

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 3:00 AM UTC
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had recent activity. 
            It will be closed in 7 days if no further activity occurs.
          close-issue-message: >
            Closing this issue due to inactivity. Feel free to reopen if it's still relevant.
          days-before-stale: 180
          days-before-close: 7
          exempt-issue-labels: 'bug,enhancement,feature'
          remove-stale-when-updated: true